### ISSUE TITLE
[BUG] - 最长回文子串

### ISSUE THREAD

**Issue by ChenPuChu** [LeetCode-Feedback/LeetCode-Feedback#25289]
### LeetCode 用户名

璞

### 问题号码、标题和链接

2.最长回文子串 https://leetcode.cn/problems/longest-palindromic-substring/description/

### Bug Category

问题限制

### 描述

我在使用c语言做这道题目时，写了一个统计字符串长度的函数，但这个函数在编译时没有通过

### 你使用的语言

C

### 你提交或者运行的代码

```bash
char *myStrtok(const char *src, int start, int num) {
    char *dest = malloc(num * sizeof(char));
    for (int i = 0; i < num; i++) {
        dest[i] = src[i + start];
    }
    return dest;
}

int myStrlen(char *src) {
    int len = 0;
    while (src[len] != 0x00) {
        len++;
    }
    return len;
}

char *longestPalindrome(char *s) {
    int size = myStrlen(s);
    if (size == 1) {
        return s;
    }
    if (size == 2 && s[0] == s[1]) {
        return s;
    }
    int start = 0, end = size - 1;
    while (start < end) {
        char c = s[start];
        char d = s[end];
        if (c != d) {
            break;
        }
        if (start == end || s[start] == s[end]) {
            return s;
        }
        start++;
        end--;
    }
    char *r1 = myStrtok(s, 0, size - 1), *r2 = myStrtok(s, 1, size - 1);
    char *s1 = longestPalindrome(r1);
    char *s2 = longestPalindrome(r2);
    int l1 = strlen(s1);
    int l2 = strlen(s2);
    return l1 > l2 ? s1 : s2;
}
```

### 期望行为

我希望编译成功通过

### 屏幕截图

```Line 12:
=================================================================
==22==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000034 at pc 0x5635fa690ac5 bp 0x7ffd8e8c3780 sp 0x7ffd8e8c3770
READ of size 1 at 0x602000000034 thread T0
    #0 0x5635fa690ac4 in myStrlen solution.c:12
    #1 0x5635fa690ac4 in longestPalindrome solution.c:12
    #2 0x5635fa6909fa in longestPalindrome solution.c:12
    #3 0x5635fa6900e3 in main solution.c:12
    #4 0x7fe77d708d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
    #5 0x7fe77d708e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
    #6 0x5635fa690584 in _start (solution+0x1e584) (BuildId: 16f6bde95983d90d3b5b82717f63e2e51d16865c)
0x602000000034 is located 0 bytes after 4-byte region [0x602000000030,0x602000000034)
allocated by thread T0 here:
    #0 0x7fe77e0ddfdf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5635fa69066e in myStrtok solution.c:12
    #2 0x5635fa6909dc in longestPalindrome solution.c:12
    #3 0x5635fa6900e3 in main solution.c:12
    #4 0x7fe77d708d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
SUMMARY: AddressSanitizer: heap-buffer-overflow solution.c:12 in myStrlen
Shadow bytes around the buggy address:
  0x601ffffffd80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x601ffffffe00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x601ffffffe80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x601fffffff00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x601fffffff80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x602000000000: fa fa 06 fa fa fa[04]fa fa fa 04 fa fa fa fa fa
  0x602000000080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x602000000100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x602000000180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x602000000200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x602000000280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==22==ABORTING```

### 额外的上下文

_No response_

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
您好，在与相关团队核实后：***不处理***（该程序在运行时发生了越界访问的运行时错误，请检查数组或指针等是否越界）。
以上信息请悉知，本次 Ticket 将关闭，感谢您的反馈和支持。
