### ISSUE TITLE
[BUG] - 需要更好的错误提示（C）

### ISSUE THREAD

**Issue by xiongnemo** [LeetCode-Feedback/LeetCode-Feedback#25618]
### LeetCode 用户名

xiongnemo

### 问题号码、标题和链接

https://leetcode.cn/problems/VvJkup/description/

### Bug Category

问题提示

### 描述

未知的报错

### 你使用的语言

C

### 你提交或者运行的代码

```bash
/**
 * Return an array of arrays of size *returnSize.
 * The sizes of the arrays are returned as *returnColumnSizes array.
 * Note: Both returned array and *columnSizes array must be malloced, assume
 * caller calls free().
 */
int** working_array = NULL;
int array_size = 0;
int current_solution_size = 0;

void swap(int* a, int* b) {
    int temp = *a;
    *a = *b;
    *b = temp;
}

void solve(int* array, int start_pos, int end_pos) {
    if (start_pos == end_pos) {
        printf("copying: [");
        for (int i = 0; i < array_size; i++) {
            printf(" %d", array[i]);
        }
        printf(" ] to pos %d (%p)\n", current_solution_size, working_array[current_solution_size]);
        memcpy(working_array[current_solution_size], array,
               sizeof(int) * array_size);
        current_solution_size += 1;
        return;
    }
    for (int i = start_pos; i <= end_pos; i++) {
        swap(&array[i], &array[start_pos]);
        solve(array, start_pos + 1, end_pos);
        swap(&array[i], &array[start_pos]);
    }
}

int** permute(int* nums, int numsSize, int* returnSize,
              int** returnColumnSizes) {
    int** return_array = NULL;
    if (numsSize == 1) {
        // 1 * 1
        *returnColumnSizes = (int*)malloc(sizeof(int) * 1);
        *returnColumnSizes[0] = 1;
        *returnSize = 1;
        return_array = (int**)malloc(sizeof(int*));
        return_array[0] = (int*)malloc(sizeof(int));
        return_array[0][0] = nums[0];
    } else {
        // n = numsSize
        // return: n * (n - 1)
        int columnSize = numsSize;
        int row_size = numsSize * (numsSize - 1);
        array_size = columnSize;
        return_array = (int**)malloc(sizeof(int*) * row_size);
        *returnColumnSizes = (int*)malloc(sizeof(int) * row_size);
        for (int i = 0; i < row_size; i++) {
            return_array[i] = (int*)malloc(sizeof(int) * columnSize);
            (*returnColumnSizes)[i] = columnSize;
        }
        working_array = return_array;
        // do dfs
        solve(nums, 0, columnSize - 1);
        *returnSize = columnSize * row_size;
        printf("returnSize=%d\n", *returnSize);
        for (int i = 0; i < row_size; i++) {
            printf("returning #%d: [", i);
            for (int j = 0; j < array_size; j++) {
                printf(" %d", return_array[i][j]);
            }
            printf(" ] from %p\n", return_array[i]);
        }
    }
    return return_array;
}
```

### 期望行为

给出一个更好的提示来协助用户处理他/她/它所提交的代码，特别是当触发 ASAN 的代码不在用户所提交的代码中？

### 额外的上下文

执行出错
```
Line 111:
=================================================================
==22==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x503000000058 at pc 0x563c3987de0f bp 0x7ffec3daf540 sp 0x7ffec3daf530
READ of size 4 at 0x503000000058 thread T0
    #0 0x563c3987de0e in _serialize_2d_array /leetcode/__Serializer__.c:241
    #1 0x563c39877e98 in main solution.c:111
    #2 0x7f81154131c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #3 0x7f811541328a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #4 0x563c39878294 in _start (solution+0x1f294) (BuildId: 32c1a50962346638cd9ec89a95020f0e1861c92c)
0x503000000058 is located 0 bytes after 24-byte region [0x503000000040,0x503000000058)
allocated by thread T0 here:
    #0 0x7f8115df79c7 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x563c3987883d in permute solution.c:111
    #2 0x563c39877e51 in main solution.c:111
    #3 0x7f81154131c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #4 0x7f811541328a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #5 0x563c39878294 in _start (solution+0x1f294) (BuildId: 32c1a50962346638cd9ec89a95020f0e1861c92c)
SUMMARY: AddressSanitizer: heap-buffer-overflow /leetcode/__Serializer__.c:241 in _serialize_2d_array
Shadow bytes around the buggy address:
  0x502ffffffd80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x502ffffffe00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x502ffffffe80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x502fffffff00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x502fffffff80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x503000000000: fa fa 00 00 00 fa fa fa 00 00 00[fa]fa fa fd fd
  0x503000000080: fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x503000000100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x503000000180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x503000000200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x503000000280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==22==ABORTING
```

标准输出
```
copying: [ 1 2 3 ] to pos 0 (0x502000000030)
copying: [ 1 3 2 ] to pos 1 (0x502000000050)
copying: [ 2 1 3 ] to pos 2 (0x502000000070)
copying: [ 2 3 1 ] to pos 3 (0x502000000090)
copying: [ 3 2 1 ] to pos 4 (0x5020000000b0)
copying: [ 3 1 2 ] to pos 5 (0x5020000000d0)
returnSize=18
returning #0: [ 1 2 3 ] from 0x502000000030
returning #1: [ 1 3 2 ] from 0x502000000050
returning #2: [ 2 1 3 ] from 0x502000000070
returning #3: [ 2 3 1 ] from 0x502000000090
returning #4: [ 3 2 1 ] from 0x5020000000b0
returning #5: [ 3 1 2 ] from 0x5020000000d0
```

最后执行的输入
nums =
`[1,2,3]`

**Comment by liyuzhu-lc** [comment]
感谢您的宝贵反馈，我们已经将您的反馈提交给我们的负责团队，并将会对相关信息进行核查，有新的进展及时再与您联系。感谢您的理解与支持。

**Comment by amcones-lc** [comment]
We have received feedback, please wait for us to process.

**Comment by luciphania** [comment]
Hi there,

Thank you for taking the time to share your feedback with us. 

After careful consideration, we have decided not to move forward with the changes suggested in your feedback.

Please know that your input is important to us. Your continued feedback is greatly appreciated as we work towards improving our platform.

Best regards,
LeetCode Support Team
